# Generated by Django 3.2.8 on 2021-10-30 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('details', models.CharField(max_length=1000)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('detail', models.CharField(max_length=50)),
                ('file', models.FileField(default='', upload_to='home/files')),
            ],
        ),
        migrations.CreateModel(
            name='Student_table',
            fields=[
                ('roll_no', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female'), ('T', 'transgender')], max_length=1)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('address', models.CharField(max_length=200)),
                ('session', models.CharField(max_length=9)),
                ('program', models.CharField(max_length=10)),
                ('semester', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Subject_table',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=50)),
                ('field', models.CharField(max_length=8)),
                ('semester', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_table',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female'), ('T', 'transgender')], max_length=1)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('degree', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tbl_attendance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attendence', models.CharField(choices=[('P', 'present'), ('A', 'absent')], max_length=1)),
                ('date', models.DateField()),
                ('stud_roll_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.student_table')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.subject_table')),
            ],
        ),
        migrations.AddField(
            model_name='subject_table',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.teacher_table'),
        ),
        migrations.CreateModel(
            name='Semester_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_no', models.CharField(max_length=1)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.subject_table')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance_table',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('program', models.CharField(max_length=10)),
                ('semester', models.CharField(max_length=1)),
                ('attendance', models.CharField(choices=[('P', 'present'), ('A', 'absent')], max_length=1)),
                ('date', models.DateField()),
                ('stud_roll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.student_table')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.subject_table')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.teacher_table')),
            ],
        ),
    ]
