# Generated by Django 3.2.8 on 2021-10-30 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_table',
            name='roll_no',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
