# Generated by Django 3.2.8 on 2021-10-31 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_student_table_roll_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject_table',
            name='id',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
