# Generated by Django 3.2.8 on 2021-10-31 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_subject_table_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_table',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='teacher_table',
            name='degree',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher_table',
            name='email',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher_table',
            name='phone',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
