# Generated by Django 3.2.8 on 2021-10-31 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20211031_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject_table',
            name='id',
            field=models.CharField(max_length=9, primary_key=True, serialize=False),
        ),
    ]
