# Generated by Django 3.2.8 on 2021-10-31 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_subject_table_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject_table',
            name='field',
            field=models.CharField(max_length=15),
        ),
    ]
