# Generated by Django 3.2.8 on 2021-10-31 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_subject_table_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester_table',
            name='field',
            field=models.CharField(default='', max_length=15),
        ),
    ]
