# Generated by Django 3.2.8 on 2021-11-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_semester_table_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_attendance',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
