# Generated by Django 3.2.8 on 2021-11-04 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_tbl_attendance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_attendance',
            name='semester',
            field=models.CharField(default=5, max_length=1),
            preserve_default=False,
        ),
    ]
