# Generated by Django 3.2.8 on 2021-11-23 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_tbl_attendance_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_table',
            name='profileImage',
            field=models.ImageField(default='', upload_to='home/profileImage'),
        ),
    ]
