# Generated by Django 3.2.8 on 2021-11-27 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_student_table_profileimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='assignment_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('closed', models.BooleanField(default=0)),
                ('given_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.teacher_table')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.subject_table')),
            ],
        ),
        migrations.CreateModel(
            name='assigment_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='home/assigments')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.student_table')),
            ],
        ),
    ]
