# Generated by Django 3.2.8 on 2021-12-01 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_assigment_data_assignment_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='subject',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.subject_table'),
        ),
    ]
