# Generated by Django 3.2.8 on 2021-12-01 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_resources_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='image',
            field=models.ImageField(default='', upload_to='home/notices'),
        ),
    ]
