# Generated by Django 3.2.8 on 2021-12-01 06:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_notice_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
