# Generated by Django 3.2.8 on 2021-12-01 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_resources_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='assigment_data',
            name='assignment',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.assignment_details'),
        ),
        migrations.AlterField(
            model_name='assignment_details',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
